### ISSUE TITLE
detailed feedback on Nomisma's elixir challenge

### ISSUE THREAD

**Issue by cjen07** [andreyleskov/weber#3]
1. the candidate's focus is mainly on data model and database which is impressive but not required
2. the candidate should fetch data from the web and not to use man-made data
the following libraries are recommended
- https://github.com/edgurgel/httpoison
- https://github.com/mischov/meeseeks
3. candidate's elixir code style, e.g in `lib/Domain/word/word.ex` not readable enough
- too many function-level pattern matching is difficult to read
- too many usage of guards should be done in another context
4. in `lib/weber_cle.ex` some details like indentation, spaces are not consistent and more function-level documentation needed
- too many `if-else` in `show` function
- in line 18, 69, 76 the indentation is not consistent, in line 22, 157 extra spaces found

**Comment by andreyleskov** [comment]
Thank you so much for your time and detailed feedback, I'll take it to improve my skills and knowledge. 

I was following these [requirements]( https://github.com/cjen07/elixir-challenge/commit/7e03dbb231b9337bf96ea772f3194535e0eadc4d).
Sorry for misinterpreting it, I should be more proactive and ask for additional information. 

[word.ex](https://github.com/andreyleskov/weber/blob/c1bcabd9abca8d56aa98ef98f504292929ddb5fa/lib/Domain/word/word.ex) is the main [aggregate](https://kalele.io/blog-posts/really-simple-cqrs/) in the application.  The code style was taken from commanded library [examples](https://github.com/commanded/commanded/blob/master/guides/Aggregates.md#example-aggregate). Please share your vision what should be improved for better readability. 

Totally agree with bad indentation and spaces, I didn't pay enough attention to it. Could you recommend a good tool for Elixir code autoformatting? What style guides would you prefer?

I had the same feeling for if-else in [show](https://github.com/andreyleskov/weber/blob/c1bcabd9abca8d56aa98ef98f504292929ddb5fa/lib/weber_cle.ex#L43) method, it is too much. I would be grateful if you could advise any ideas how to improve view logic for the command line and how to print viewmodels in a more functional way.

I really appreciate your feedback and time, hope to hear from you.

**Comment by cjen07** [comment]
Hi,

sorry for the late reply

- `mix format` for code format in elixir
- code style in elixir is flexible, just make it reasonably readable by defining context boundaries, refactoring functions and adding docs
- It's not all your fault misinterpreting it, the question was unclear
- by the way, the challenge is actually to make a real elixir tool that one can actually use, so if you think in this way, it's not hard to get that we need to fetch data from internet

hopefully it helps

Thanks
Wang Chen
